baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sonic Lobster | Portland, Maine Cover Band'

theme = "cyberscape"

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true
