baseURL = 'https://soniclobstermaine.band/'
languageCode = 'en-us'
title = 'Sonic Lobster | Portland, Maine Cover Band'

theme = "cyberscape"

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true

[[menu.main]]
name = "Upcoming Shows"
url = "/upcoming-shows"
weight = 1

[[menu.main]]
name = "Lineup"
url = "/lineup"
weight = 2

[[menu.main]]
name = "Contact Us"
url = "/contact"
weight = 3
